services:
    backend:
        container_name: backend
        restart: always

    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always

    redis:
        container_name: redis
        image: redis:latest
        restart: always

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:latest
        restart: always

    celery:
        container_name: celery
        restart: always

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
